# Generated by Django 5.2.7 on 2025-11-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task_type', models.CharField(db_index=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('current_building', models.CharField(choices=[('girls_hostel', 'Girls Hostel'), ('boys_hostel_old', 'Boys Hostel (Old)'), ('boys_hostel_h1', 'Boys Hostel (H1)'), ('boys_hostel_h2', 'Boys Hostel (H2)'), ('lhc', 'LHC (Lecture Hall Complex)'), ('rnd', 'R&D Building'), ('academic', 'Old Academic Building'), ('guest_house', 'Guest House'), ('library', 'Library')], default='academic', max_length=50)),
                ('current_wing', models.CharField(blank=True, help_text="e.g., 'A', 'B', 'North', etc.", max_length=10, null=True)),
                ('current_location_floor', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy')], default='free', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(db_index=True, max_length=50)),
                ('building', models.CharField(choices=[('girls_hostel', 'Girls Hostel'), ('boys_hostel_old', 'Boys Hostel (Old)'), ('boys_hostel_h1', 'Boys Hostel (H1)'), ('boys_hostel_h2', 'Boys Hostel (H2)'), ('lhc', 'LHC (Lecture Hall Complex)'), ('rnd', 'R&D Building'), ('academic', 'Old Academic Building'), ('guest_house', 'Guest House'), ('library', 'Library')], db_index=True, max_length=50)),
                ('wing', models.CharField(blank=True, help_text="e.g., 'A', 'B', 'C' for Old Boys Hostel", max_length=10, null=True)),
                ('location_floor', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='fms_api.staff')),
            ],
        ),
    ]
